PORTFOLIO_NAME: "Global"

DATA_PATH: "data/"
RESULTS_PATH: "results/"

# Benchmark for the portfolio:
BENCHMARK_TICKERS: ["VEA", "VTI"]
BENCHMARK_TICKER_WEIGHTS: [.4, .6]

# This is only used for including data not accessible via the APIs
CUSTOM_DATA_LIST: []

ENVIRONMENTS:
  # Good assets for Rising Growth:
  # - Equities,
  # - Commodities,
  # - Corporate credit,
  # - EM credit
  RISING_GROWTH: ["VEA", "VTI", "EEM"]

  # Good assets for Falling Growth:
  # - Nominal bonds,
  # - Inflation-linked bonds
  FALLING_GROWTH: ["BWX", "TLT"]

  #  Good assests for Rising Inflation:
  # - Inflation-linked bonds
  # - Commodities
  # - Gold
  # - EM credit
  RISING_INFLATION: ["GLD", "DBC", "EMB"]

  # Good assests for Falling Inflation:
  # - Equities
  # - Nominal bonds (long term?)
  FALLING_INFLATION: ["VEA", "VTI", "TLT"]
